name: severity template
description: severity template
title: "My Issue Template"
about: A template for creating issues
labels:
  - bug
assignees:
  - octocat
body:
  - type: dropdown
    id: severity
    attributes:
      label: Severity
      options:
        - High
        - Medium
        - Low
    validations:
      required: true
      validationMessage: Please select a severity level for this issue.
  - type: input
    id: description
    attributes:
      label: Description
      description: Please provide a brief description of the issue.
    validations:
      required: true
      validationMessage: Please provide a description for this issue.
