name: education Workflow

on:
  issues:
    types: [opened]
    # Filter by issue template name
    issue_template:
      name: education template

jobs:
  process_issue:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Print issue information
        run: |
          echo "Issue number: ${{ github.event.issue.number }}"
          echo "Issue title: ${{ github.event.issue.title }}"
          echo "Issue description: ${{ github.event.issue.body }}"
          echo "Assignee: ${{ github.event.issue.assignee.login }}"
