name: Sample Workflow

on:
  issues:
    types: [opened]
  # Only run for issues with the "education template" template
  workflow_dispatch:
    inputs:
      template:
        description: 'Issue template'
        required: true
        default: 'sample template'

jobs:
  process_issue:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Print issue information
        run: |
          echo "Issue number: ${{ github.event.issue.number }}"
          echo "Issue title: ${{ github.event.issue.title }}"
         