name: Severity Workflow
on:
  issues:
    types: [opened]
    # Only run for issues with the "sample" label
    labels: [documentation]

jobs:
  process_issue:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Print issue information
        run: |
          echo "Issue number: ${{ github.event.issue.number }}"
          echo "Issue title: ${{ github.event.issue.title }}"
          echo "Issue description: ${{ github.event.issue.body }}"
          echo "Assignee: ${{ github.event.issue.assignee.login }}"
